services:
  sbtdev-docker:
    container_name: ci4-docker
    build: .
    volumes:
      - ./ci4proj:/var/www/html
    ports:
      - 8080:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: hellodemo
      MYSQL_DATABASE: ci4proj_db
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  # webserver:
  #   build: .
  #   # image: httpd:latest //  if you want to use the Apache web server image
  #   volumes:
  #     - ./sbtdev:/var/www/html/writable/
  #   user: "www-data"
